name: Daily Stock Analysis  # 工作流名称

on:
  push:
    branches: [ main ]      # 当你修改代码时触发
  workflow_dispatch:        # 重要：这个就是那个“Run workflow”手动按钮的开关
  schedule:
    - cron: '0 1 * * *'     # 定时触发（北京时间每天上午9点）

jobs:
  build:
    runs-on: ubuntu-latest  # 使用 GitHub 的云端 Linux 服务器

    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 安装 Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 安装依赖
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: 运行主程序
        run: python main.py
